name:                lab
version:             0.1.0.0
github:              "ShinKage/lci-2019"
license:             BSD3
author:              "Giuseppe Lomurno"
maintainer:          "lomurno.giuseppe97@gmail.com"
copyright:           "2019 Giuseppe Lomurno"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ShinKage/lab#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - llvm-hs-pure
  - llvm-hs
  - llvm-hs-pretty
  - prettyprinter
  - prettyprinter-ansi-terminal
  - singletons
  - megaparsec
  - parser-combinators
  - mtl
  - bytestring
  - libffi
  - haskeline
  - storable-tuple
  - unordered-containers
  - hashable

library:
  source-dirs: src

executables:
  lab-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wno-unticked-promoted-constructors
    dependencies:
    - lab

tests:
  lab-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab
